/* Created by Conner recoskie
   March 31, 2022
   This program uses pre-defined math methods to output answers to questions a 
   user may have. 
 */

public class FrmCalculate extends javax.swing.JFrame {
    // Declaring double variables for the "largested of two numbers" question.
    double largeResponse1;
    double largeResponse2;
    double largeAnswer;
    
    // Declaring double variables for the "smallest of two numbers" question.
    double smallResponse1;
    double smallResponse2;
    double smallAnswer;
    
    // Declaring double variables for the "number to a power" question. 
    double powerResponse1;
    double powerResponse2;
    double powerAnswer;
    
    // Declaring double variables for the hypotenuse question.
    double hypotenuseResponse1;
    double hypotenuseResponse2;
    double hypotenuseAnswer;
    
    // Declaring double variables for the "round down" question.
    double roundDownResponse;
    double roundDownAnswer;
    
    // Declaring double variables for the "round up" question.
    double roundUpResponse;
    double roundUpAnswer;
    
    // Declaring double variables for the square root question.
    double squareRootResponse;
    double squareRootAnswer;
    
    // Declaring double variables for the "degrees to radians" question.
    double radiansResponse;
    double radiansAnswer;
    
    
    public FrmCalculate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txtInstructions1 = new javax.swing.JLabel();
        txtLargeInput1 = new javax.swing.JTextField();
        txtLargeInput2 = new javax.swing.JTextField();
        txtInstructions2 = new javax.swing.JLabel();
        txtSmallInput1 = new javax.swing.JTextField();
        txtSmallInput2 = new javax.swing.JTextField();
        txtInstructions3 = new javax.swing.JLabel();
        lblPowerInput1 = new javax.swing.JTextField();
        lblPowerInput2 = new javax.swing.JTextField();
        txtInstructions14 = new javax.swing.JLabel();
        lblHypotenuseInput1 = new javax.swing.JTextField();
        lblHypotenuseInput2 = new javax.swing.JTextField();
        txtInstructions5 = new javax.swing.JLabel();
        txtRoundDownInput = new javax.swing.JTextField();
        txtInstructions6 = new javax.swing.JLabel();
        txtRoundUpInput = new javax.swing.JTextField();
        txtInstructions7 = new javax.swing.JLabel();
        txtSquareRootInput = new javax.swing.JTextField();
        txtInstructions8 = new javax.swing.JLabel();
        txtRadiansInput = new javax.swing.JTextField();
        btnLarge = new javax.swing.JButton();
        btnSmallest = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnHypotenuse = new javax.swing.JButton();
        btnRoundDown = new javax.swing.JButton();
        btnRoundedUp = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnRadians = new javax.swing.JButton();
        lblLargeAnswer = new javax.swing.JLabel();
        lblSmallAnswer = new javax.swing.JLabel();
        lblPowerAnswer = new javax.swing.JLabel();
        lblHypotenuseAnswer = new javax.swing.JLabel();
        lblRoundDownResponse = new javax.swing.JLabel();
        lblRoundUpResponse = new javax.swing.JLabel();
        lblSquareRootResponse = new javax.swing.JLabel();
        lblRadiansResponse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitle.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(0, 51, 255));
        txtTitle.setText("Magical Math Methods");

        txtInstructions1.setText("Enter two numbers and click the button. The program will display the largest of the two numbers:");

        txtLargeInput2.setText(" ");

        txtInstructions2.setText("Enter two numbers and click the button. The program will display the smallest of the two numbers:");

        txtInstructions3.setText("Enter two numbers and click the button. The program will display the first number to the power of the second:");

        txtInstructions14.setText("Enter the length of two sides of a right angle triangle. The program will display the hypotenuse of the triangle:");

        txtInstructions5.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer:");

        txtInstructions6.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer:");

        txtInstructions7.setText("Enter an integer. The program will display the square root of the integer:");

        txtInstructions8.setText("Enter an angle in degrees. The program will display the angle in radians:");

        btnLarge.setText("Largest");
        btnLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLargeActionPerformed(evt);
            }
        });

        btnSmallest.setText("Smallest");
        btnSmallest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmallestActionPerformed(evt);
            }
        });

        btnPower.setText("To the power of...");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });

        btnHypotenuse.setText("Hypotenuse");
        btnHypotenuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHypotenuseActionPerformed(evt);
            }
        });

        btnRoundDown.setText("Rounded down");
        btnRoundDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoundDownActionPerformed(evt);
            }
        });

        btnRoundedUp.setText("Rounded up");
        btnRoundedUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoundedUpActionPerformed(evt);
            }
        });

        btnSquareRoot.setText("Square Root");
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });

        btnRadians.setText("In Radians");
        btnRadians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadiansActionPerformed(evt);
            }
        });

        lblLargeAnswer.setText("-");

        lblSmallAnswer.setText("-");

        lblPowerAnswer.setText("-");

        lblHypotenuseAnswer.setText("-");

        lblRoundDownResponse.setText("-");

        lblRoundUpResponse.setText("-");

        lblSquareRootResponse.setText("-");

        lblRadiansResponse.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(txtSmallInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtSmallInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnSmallest)
                        .addGap(74, 74, 74)
                        .addComponent(lblSmallAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lblPowerInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblPowerInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(btnPower)
                                .addGap(18, 18, 18)
                                .addComponent(lblPowerAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtInstructions2)
                            .addComponent(txtInstructions3)
                            .addComponent(txtInstructions14)
                            .addComponent(txtInstructions5)
                            .addComponent(txtInstructions6)
                            .addComponent(txtInstructions7)
                            .addComponent(txtInstructions8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtLargeInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(txtLargeInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(121, 121, 121)
                                    .addComponent(btnLarge)
                                    .addGap(76, 76, 76)
                                    .addComponent(lblLargeAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtInstructions1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblHypotenuseInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblHypotenuseInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnHypotenuse)
                        .addGap(55, 55, 55)
                        .addComponent(lblHypotenuseAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtRadiansInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(btnRadians)
                                .addGap(72, 72, 72)
                                .addComponent(lblRadiansResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtSquareRootInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(btnSquareRoot)
                                .addGap(59, 59, 59)
                                .addComponent(lblSquareRootResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(txtTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRoundUpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(btnRoundedUp)
                                .addGap(57, 57, 57)
                                .addComponent(lblRoundUpResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtRoundDownInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(btnRoundDown)
                                .addGap(38, 38, 38)
                                .addComponent(lblRoundDownResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInstructions1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLargeInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLargeInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLarge)
                    .addComponent(lblLargeAnswer))
                .addGap(35, 35, 35)
                .addComponent(txtInstructions2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSmallInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSmallInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmallest)
                    .addComponent(lblSmallAnswer))
                .addGap(35, 35, 35)
                .addComponent(txtInstructions3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPowerInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPowerInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPower)
                    .addComponent(lblPowerAnswer))
                .addGap(35, 35, 35)
                .addComponent(txtInstructions14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHypotenuseInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHypotenuseInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHypotenuse)
                    .addComponent(lblHypotenuseAnswer))
                .addGap(35, 35, 35)
                .addComponent(txtInstructions5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRoundDownInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoundDown)
                    .addComponent(lblRoundDownResponse))
                .addGap(35, 35, 35)
                .addComponent(txtInstructions6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRoundUpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoundedUp)
                    .addComponent(lblRoundUpResponse))
                .addGap(35, 35, 35)
                .addComponent(txtInstructions7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSquareRootInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSquareRoot)
                    .addComponent(lblSquareRootResponse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(txtInstructions8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRadiansInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRadians)
                        .addComponent(lblRadiansResponse)))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLargeActionPerformed
        // Adding the users input to variables. 
        largeResponse1 = Double.parseDouble(txtLargeInput1.getText());
        largeResponse2 = Double.parseDouble(txtLargeInput2.getText());
        
        // Calculating the users answer using a pre-defined math method.
        largeAnswer = Math.max(largeResponse1, largeResponse2);
        
        // Outputting the users answer to the GUI.
        lblLargeAnswer.setText(String.valueOf("The answer is: " +
                largeAnswer + "."));   
    }//GEN-LAST:event_btnLargeActionPerformed

    private void btnSmallestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmallestActionPerformed
        // Adding the users input to variables.
        smallResponse1 = Double.parseDouble(txtSmallInput1.getText());
        smallResponse2 = Double.parseDouble(txtSmallInput2.getText());
        
        // Calculating the users answer using a pre-defined math method.
        smallAnswer = Math.min(smallResponse1, smallResponse2);
        
        // Outputting the users answer to the GUI.
        lblSmallAnswer.setText(String.valueOf("The answer is: " + 
                smallAnswer + "."));
    }//GEN-LAST:event_btnSmallestActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        // Adding the users input to variables.
        powerResponse1 = Double.parseDouble(lblPowerInput1.getText());
        powerResponse2 = Double.parseDouble(lblPowerInput2.getText());
        
        // Calculating the users answer using a pre-defined math method.
        powerAnswer = Math.pow(powerResponse1, powerResponse2);
        
        // Rounding the users answer.
        powerAnswer = powerAnswer * 100;
        powerAnswer = Math.round(powerAnswer);
        powerAnswer = powerAnswer/100;
        
        // Outputting the users answer to the GUI.
        lblPowerAnswer.setText(String.valueOf("The answer is: " + powerAnswer +
                "."));
    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnHypotenuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHypotenuseActionPerformed
        // Adding the users input to variables.
        hypotenuseResponse1 = Double.parseDouble(lblHypotenuseInput1.getText());
        hypotenuseResponse2 = Double.parseDouble(lblHypotenuseInput2.getText());
        
        // Calculating the users answer using a pre-defined math method.
        hypotenuseAnswer = Math.hypot(hypotenuseResponse1, hypotenuseResponse2);
        
        // Rounding the users answer.
        hypotenuseAnswer = hypotenuseAnswer * 100;
        hypotenuseAnswer = Math.round(hypotenuseAnswer);
        hypotenuseAnswer = hypotenuseAnswer/100; 
        
        // Outputting the users answer to the GUI.
        lblHypotenuseAnswer.setText(String.valueOf("The answer is: " +
                hypotenuseAnswer + "."));
    }//GEN-LAST:event_btnHypotenuseActionPerformed

    private void btnRoundDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoundDownActionPerformed
         // Adding the users input to a variable.
        roundDownResponse = Double.parseDouble(txtRoundDownInput.getText());
        
        // Calculating the users answer using a pre-defined math method.
        roundDownAnswer = Math.floor(roundDownResponse);
        
        // Outputting the users answer to the GUI.
        lblRoundDownResponse.setText(String.valueOf("The answer is: " +
                roundDownAnswer));
    }//GEN-LAST:event_btnRoundDownActionPerformed

    private void btnRoundedUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoundedUpActionPerformed
         // Adding the users input to a variable.
        roundUpResponse = Double.parseDouble(txtRoundUpInput.getText());
        
        // Calculating the users answer using a pre-defined math method.
        roundUpAnswer = Math.ceil(roundUpResponse);
        
        // Outputting the users answer to the GUI.
        lblRoundUpResponse.setText(String.valueOf("The answer is: " +
                roundUpAnswer));
    }//GEN-LAST:event_btnRoundedUpActionPerformed

    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
        // Adding the users input to a variable.
        squareRootResponse = Double.parseDouble(txtSquareRootInput.getText());
        
        // Calculating the users answer using a pre-defined math method.
        squareRootAnswer = Math.sqrt(squareRootResponse);
        
        // Rounding the users answer.
        squareRootAnswer = squareRootAnswer * 100;
        squareRootAnswer = Math.round(squareRootAnswer);
        squareRootAnswer = squareRootAnswer/100;
        
        // Outputting the users answer to the GUI.
        lblSquareRootResponse.setText(String.valueOf("The answer is: " + 
                squareRootAnswer));
    }//GEN-LAST:event_btnSquareRootActionPerformed

    private void btnRadiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadiansActionPerformed
        // Adding the users input to a variable.
        radiansResponse = Double.parseDouble(txtRadiansInput.getText());
        
        // Calculating the users answer using a pre-defined math method.
        radiansAnswer = Math.toRadians(radiansResponse);
        
        // Rounding the users answer.
        radiansAnswer = radiansAnswer * 100;
        radiansAnswer = Math.round(radiansAnswer);
        radiansAnswer = radiansAnswer/100;
        
        // Outputting the users answer to the GUI.
        lblRadiansResponse.setText(String.valueOf("The answer is: " + 
               radiansAnswer));
    }//GEN-LAST:event_btnRadiansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCalculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHypotenuse;
    private javax.swing.JButton btnLarge;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnRadians;
    private javax.swing.JButton btnRoundDown;
    private javax.swing.JButton btnRoundedUp;
    private javax.swing.JButton btnSmallest;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JLabel lblHypotenuseAnswer;
    private javax.swing.JTextField lblHypotenuseInput1;
    private javax.swing.JTextField lblHypotenuseInput2;
    private javax.swing.JLabel lblLargeAnswer;
    private javax.swing.JLabel lblPowerAnswer;
    private javax.swing.JTextField lblPowerInput1;
    private javax.swing.JTextField lblPowerInput2;
    private javax.swing.JLabel lblRadiansResponse;
    private javax.swing.JLabel lblRoundDownResponse;
    private javax.swing.JLabel lblRoundUpResponse;
    private javax.swing.JLabel lblSmallAnswer;
    private javax.swing.JLabel lblSquareRootResponse;
    private javax.swing.JLabel txtInstructions1;
    private javax.swing.JLabel txtInstructions14;
    private javax.swing.JLabel txtInstructions2;
    private javax.swing.JLabel txtInstructions3;
    private javax.swing.JLabel txtInstructions5;
    private javax.swing.JLabel txtInstructions6;
    private javax.swing.JLabel txtInstructions7;
    private javax.swing.JLabel txtInstructions8;
    private javax.swing.JTextField txtLargeInput1;
    private javax.swing.JTextField txtLargeInput2;
    private javax.swing.JTextField txtRadiansInput;
    private javax.swing.JTextField txtRoundDownInput;
    private javax.swing.JTextField txtRoundUpInput;
    private javax.swing.JTextField txtSmallInput1;
    private javax.swing.JTextField txtSmallInput2;
    private javax.swing.JTextField txtSquareRootInput;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
